# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.proto import action_service_pb2 as action__service__pb2
from core.proto import base_pb2 as base__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in action_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActionRecognitionStub(object):
    """Video Action Recognition Service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/action.ActionRecognition/Predict',
                request_serializer=action__service__pb2.ActionRequest.SerializeToString,
                response_deserializer=action__service__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/action.ActionRecognition/LoadModel',
                request_serializer=base__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=base__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/action.ActionRecognition/UnloadModel',
                request_serializer=base__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=base__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/action.ActionRecognition/ListModels',
                request_serializer=base__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=base__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/action.ActionRecognition/HealthCheck',
                request_serializer=base__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=base__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ActionRecognitionServicer(object):
    """Video Action Recognition Service.
    """

    def Predict(self, request, context):
        """Run action recognition on one or more video sequences.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Load an action recognition model onto a device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Unload an action recognition model from a device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List loaded action recognition models.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=action__service__pb2.ActionRequest.FromString,
                    response_serializer=action__service__pb2.ActionResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=base__pb2.LoadModelRequest.FromString,
                    response_serializer=base__pb2.ModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=base__pb2.UnloadModelRequest.FromString,
                    response_serializer=base__pb2.ModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=base__pb2.ListModelsRequest.FromString,
                    response_serializer=base__pb2.ListModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=base__pb2.HealthCheckRequest.FromString,
                    response_serializer=base__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'action.ActionRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('action.ActionRecognition', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionRecognition(object):
    """Video Action Recognition Service.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionRecognition/Predict',
            action__service__pb2.ActionRequest.SerializeToString,
            action__service__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionRecognition/LoadModel',
            base__pb2.LoadModelRequest.SerializeToString,
            base__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionRecognition/UnloadModel',
            base__pb2.UnloadModelRequest.SerializeToString,
            base__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionRecognition/ListModels',
            base__pb2.ListModelsRequest.SerializeToString,
            base__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionRecognition/HealthCheck',
            base__pb2.HealthCheckRequest.SerializeToString,
            base__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
