# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'action_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x63tion_service.proto\x12\x06\x61\x63tion\x1a\nbase.proto\"3\n\x0c\x41\x63tionParams\x12#\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x15.base.InferenceParams\"\x82\x01\n\x0c\x41\x63tionResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x13\n\x0bsequence_id\x18\x03 \x01(\x05\x12(\n\ncache_info\x18\x04 \x01(\x0b\x32\x14.base.ImageCacheInfo\x12\x10\n\x08\x63lass_id\x18\x05 \x01(\x05\"\x8a\x01\n\rActionRequest\x12+\n\x0erequest_header\x18\x01 \x01(\x0b\x32\x13.base.RequestHeader\x12&\n\tsequences\x18\x02 \x03(\x0b\x32\x13.base.ImageSequence\x12$\n\x06params\x18\x03 \x01(\x0b\x32\x14.action.ActionParams\"\x91\x01\n\x0e\x41\x63tionResponse\x12-\n\x0fresponse_header\x18\x01 \x01(\x0b\x32\x14.base.ResponseHeader\x12%\n\x07results\x18\x02 \x03(\x0b\x32\x14.action.ActionResult\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t2\xca\x02\n\x11\x41\x63tionRecognition\x12\x38\n\x07Predict\x12\x15.action.ActionRequest\x1a\x16.action.ActionResponse\x12\x38\n\tLoadModel\x12\x16.base.LoadModelRequest\x1a\x13.base.ModelResponse\x12<\n\x0bUnloadModel\x12\x18.base.UnloadModelRequest\x1a\x13.base.ModelResponse\x12?\n\nListModels\x12\x17.base.ListModelsRequest\x1a\x18.base.ListModelsResponse\x12\x42\n\x0bHealthCheck\x12\x18.base.HealthCheckRequest\x1a\x19.base.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONPARAMS']._serialized_start=44
  _globals['_ACTIONPARAMS']._serialized_end=95
  _globals['_ACTIONRESULT']._serialized_start=98
  _globals['_ACTIONRESULT']._serialized_end=228
  _globals['_ACTIONREQUEST']._serialized_start=231
  _globals['_ACTIONREQUEST']._serialized_end=369
  _globals['_ACTIONRESPONSE']._serialized_start=372
  _globals['_ACTIONRESPONSE']._serialized_end=517
  _globals['_ACTIONRECOGNITION']._serialized_start=520
  _globals['_ACTIONRECOGNITION']._serialized_end=850
# @@protoc_insertion_point(module_scope)
