# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classification_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63lassification_service.proto\x12\x0e\x63lassification\x1a\nbase.proto\";\n\x14\x43lassificationParams\x12#\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x15.base.InferenceParams\"\x87\x01\n\x14\x43lassificationResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08image_id\x18\x03 \x01(\x05\x12(\n\ncache_info\x18\x04 \x01(\x0b\x32\x14.base.ImageCacheInfo\x12\x10\n\x08\x63lass_id\x18\x05 \x01(\x05\"\x97\x01\n\x15\x43lassificationRequest\x12+\n\x0erequest_header\x18\x01 \x01(\x0b\x32\x13.base.RequestHeader\x12\x1b\n\x06images\x18\x02 \x03(\x0b\x32\x0b.base.Image\x12\x34\n\x06params\x18\x03 \x01(\x0b\x32$.classification.ClassificationParams\"\xa9\x01\n\x16\x43lassificationResponse\x12-\n\x0fresponse_header\x18\x01 \x01(\x0b\x32\x14.base.ResponseHeader\x12\x35\n\x07results\x18\x02 \x03(\x0b\x32$.classification.ClassificationResult\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t2\xec\x02\n\x13ImageClassification\x12X\n\x07Predict\x12%.classification.ClassificationRequest\x1a&.classification.ClassificationResponse\x12\x38\n\tLoadModel\x12\x16.base.LoadModelRequest\x1a\x13.base.ModelResponse\x12<\n\x0bUnloadModel\x12\x18.base.UnloadModelRequest\x1a\x13.base.ModelResponse\x12?\n\nListModels\x12\x17.base.ListModelsRequest\x1a\x18.base.ListModelsResponse\x12\x42\n\x0bHealthCheck\x12\x18.base.HealthCheckRequest\x1a\x19.base.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFICATIONPARAMS']._serialized_start=60
  _globals['_CLASSIFICATIONPARAMS']._serialized_end=119
  _globals['_CLASSIFICATIONRESULT']._serialized_start=122
  _globals['_CLASSIFICATIONRESULT']._serialized_end=257
  _globals['_CLASSIFICATIONREQUEST']._serialized_start=260
  _globals['_CLASSIFICATIONREQUEST']._serialized_end=411
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=414
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=583
  _globals['_IMAGECLASSIFICATION']._serialized_start=586
  _globals['_IMAGECLASSIFICATION']._serialized_end=950
# @@protoc_insertion_point(module_scope)
