# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.proto import base_pb2 as base__pb2
from core.proto import detection_service_pb2 as detection__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in detection_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectDetectionStub(object):
    """Object Detection Service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/detection.ObjectDetection/Predict',
                request_serializer=detection__service__pb2.DetectionRequest.SerializeToString,
                response_deserializer=detection__service__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/detection.ObjectDetection/LoadModel',
                request_serializer=base__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=base__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/detection.ObjectDetection/UnloadModel',
                request_serializer=base__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=base__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/detection.ObjectDetection/ListModels',
                request_serializer=base__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=base__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/detection.ObjectDetection/HealthCheck',
                request_serializer=base__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=base__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ObjectDetectionServicer(object):
    """Object Detection Service.
    """

    def Predict(self, request, context):
        """Run object detection on one or more images.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Load a detection model onto a device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Unload a detection model from a device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List loaded detection models.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=detection__service__pb2.DetectionRequest.FromString,
                    response_serializer=detection__service__pb2.DetectionResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=base__pb2.LoadModelRequest.FromString,
                    response_serializer=base__pb2.ModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=base__pb2.UnloadModelRequest.FromString,
                    response_serializer=base__pb2.ModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=base__pb2.ListModelsRequest.FromString,
                    response_serializer=base__pb2.ListModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=base__pb2.HealthCheckRequest.FromString,
                    response_serializer=base__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detection.ObjectDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('detection.ObjectDetection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectDetection(object):
    """Object Detection Service.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.ObjectDetection/Predict',
            detection__service__pb2.DetectionRequest.SerializeToString,
            detection__service__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.ObjectDetection/LoadModel',
            base__pb2.LoadModelRequest.SerializeToString,
            base__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.ObjectDetection/UnloadModel',
            base__pb2.UnloadModelRequest.SerializeToString,
            base__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.ObjectDetection/ListModels',
            base__pb2.ListModelsRequest.SerializeToString,
            base__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.ObjectDetection/HealthCheck',
            base__pb2.HealthCheckRequest.SerializeToString,
            base__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
