# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detection_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x65tection_service.proto\x12\tdetection\x1a\nbase.proto\"o\n\x0f\x44\x65tectionParams\x12#\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x15.base.InferenceParams\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x01\x12\x19\n\x11nms_iou_threshold\x18\x03 \x01(\x01\"~\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x05\x12\r\n\x05y_min\x18\x02 \x01(\x05\x12\r\n\x05x_max\x18\x03 \x01(\x05\x12\r\n\x05y_max\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\x12\r\n\x05label\x18\x07 \x01(\t\"\x84\x01\n\x10\x44\x65tectionResults\x12\r\n\x05names\x18\x01 \x03(\t\x12%\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\x16.detection.BoundingBox\x12\x10\n\x08image_id\x18\x03 \x01(\x05\x12(\n\ncache_info\x18\x04 \x01(\x0b\x32\x14.base.ImageCacheInfo\"\x88\x01\n\x10\x44\x65tectionRequest\x12+\n\x0erequest_header\x18\x01 \x01(\x0b\x32\x13.base.RequestHeader\x12\x1b\n\x06images\x18\x02 \x03(\x0b\x32\x0b.base.Image\x12*\n\x06params\x18\x03 \x01(\x0b\x32\x1a.detection.DetectionParams\"\x9b\x01\n\x11\x44\x65tectionResponse\x12-\n\x0fresponse_header\x18\x01 \x01(\x0b\x32\x14.base.ResponseHeader\x12,\n\x07results\x18\x02 \x03(\x0b\x32\x1b.detection.DetectionResults\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t2\xd4\x02\n\x0fObjectDetection\x12\x44\n\x07Predict\x12\x1b.detection.DetectionRequest\x1a\x1c.detection.DetectionResponse\x12\x38\n\tLoadModel\x12\x16.base.LoadModelRequest\x1a\x13.base.ModelResponse\x12<\n\x0bUnloadModel\x12\x18.base.UnloadModelRequest\x1a\x13.base.ModelResponse\x12?\n\nListModels\x12\x17.base.ListModelsRequest\x1a\x18.base.ListModelsResponse\x12\x42\n\x0bHealthCheck\x12\x18.base.HealthCheckRequest\x1a\x19.base.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONPARAMS']._serialized_start=50
  _globals['_DETECTIONPARAMS']._serialized_end=161
  _globals['_BOUNDINGBOX']._serialized_start=163
  _globals['_BOUNDINGBOX']._serialized_end=289
  _globals['_DETECTIONRESULTS']._serialized_start=292
  _globals['_DETECTIONRESULTS']._serialized_end=424
  _globals['_DETECTIONREQUEST']._serialized_start=427
  _globals['_DETECTIONREQUEST']._serialized_end=563
  _globals['_DETECTIONRESPONSE']._serialized_start=566
  _globals['_DETECTIONRESPONSE']._serialized_end=721
  _globals['_OBJECTDETECTION']._serialized_start=724
  _globals['_OBJECTDETECTION']._serialized_end=1064
# @@protoc_insertion_point(module_scope)
