# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\x0c\x65mailservice\"B\n\nAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"\xf0\x02\n\x10SendEmailRequest\x12\x14\n\x0c\x66rom_address\x18\x01 \x01(\t\x12\x16\n\x0e\x66rom_auth_code\x18\x02 \x01(\t\x12\x14\n\x0cto_addresses\x18\x03 \x03(\t\x12\x14\n\x0c\x63\x63_addresses\x18\x04 \x03(\t\x12\x15\n\rbcc_addresses\x18\x05 \x03(\t\x12\x0f\n\x07subject\x18\x06 \x01(\t\x12\x11\n\thtml_body\x18\x07 \x01(\t\x12\x17\n\x0fplain_text_body\x18\x08 \x01(\t\x12-\n\x0b\x61ttachments\x18\t \x03(\x0b\x32\x18.emailservice.Attachment\x12I\n\x0e\x63ustom_headers\x18\n \x03(\x0b\x32\x31.emailservice.SendEmailRequest.CustomHeadersEntry\x1a\x34\n\x12\x43ustomHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x11SendEmailResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x65mail_id\x18\x03 \x01(\t2\\\n\x0c\x45mailService\x12L\n\tSendEmail\x12\x1e.emailservice.SendEmailRequest\x1a\x1f.emailservice.SendEmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDEMAILREQUEST_CUSTOMHEADERSENTRY']._loaded_options = None
  _globals['_SENDEMAILREQUEST_CUSTOMHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_ATTACHMENT']._serialized_start=29
  _globals['_ATTACHMENT']._serialized_end=95
  _globals['_SENDEMAILREQUEST']._serialized_start=98
  _globals['_SENDEMAILREQUEST']._serialized_end=466
  _globals['_SENDEMAILREQUEST_CUSTOMHEADERSENTRY']._serialized_start=414
  _globals['_SENDEMAILREQUEST_CUSTOMHEADERSENTRY']._serialized_end=466
  _globals['_SENDEMAILRESPONSE']._serialized_start=468
  _globals['_SENDEMAILRESPONSE']._serialized_end=538
  _globals['_EMAILSERVICE']._serialized_start=540
  _globals['_EMAILSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
