# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.proto import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ocr_service.proto\x12\x03ocr\x1a\nbase.proto\"e\n\tOCRParams\x12#\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x15.base.InferenceParams\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x01\x12\x15\n\rlanguage_hint\x18\x03 \x01(\t\"\\\n\tTextBlock\x12\x1b\n\x06points\x18\x01 \x03(\x0b\x32\x0b.base.Point\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08language\x18\x04 \x01(\t\"h\n\nOCRResults\x12\x1e\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x0e.ocr.TextBlock\x12\x10\n\x08image_id\x18\x02 \x01(\x05\x12(\n\ncache_info\x18\x03 \x01(\x0b\x32\x14.base.ImageCacheInfo\"v\n\nOCRRequest\x12+\n\x0erequest_header\x18\x01 \x01(\x0b\x32\x13.base.RequestHeader\x12\x1b\n\x06images\x18\x02 \x03(\x0b\x32\x0b.base.Image\x12\x1e\n\x06params\x18\x03 \x01(\x0b\x32\x0e.ocr.OCRParams\"\x89\x01\n\x0bOCRResponse\x12-\n\x0fresponse_header\x18\x01 \x01(\x0b\x32\x14.base.ResponseHeader\x12 \n\x07results\x18\x02 \x03(\x0b\x32\x0f.ocr.OCRResults\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t2\xc8\x02\n\x1bOpticalCharacterRecognition\x12,\n\x07Predict\x12\x0f.ocr.OCRRequest\x1a\x10.ocr.OCRResponse\x12\x38\n\tLoadModel\x12\x16.base.LoadModelRequest\x1a\x13.base.ModelResponse\x12<\n\x0bUnloadModel\x12\x18.base.UnloadModelRequest\x1a\x13.base.ModelResponse\x12?\n\nListModels\x12\x17.base.ListModelsRequest\x1a\x18.base.ListModelsResponse\x12\x42\n\x0bHealthCheck\x12\x18.base.HealthCheckRequest\x1a\x19.base.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRPARAMS']._serialized_start=38
  _globals['_OCRPARAMS']._serialized_end=139
  _globals['_TEXTBLOCK']._serialized_start=141
  _globals['_TEXTBLOCK']._serialized_end=233
  _globals['_OCRRESULTS']._serialized_start=235
  _globals['_OCRRESULTS']._serialized_end=339
  _globals['_OCRREQUEST']._serialized_start=341
  _globals['_OCRREQUEST']._serialized_end=459
  _globals['_OCRRESPONSE']._serialized_start=462
  _globals['_OCRRESPONSE']._serialized_end=599
  _globals['_OPTICALCHARACTERRECOGNITION']._serialized_start=602
  _globals['_OPTICALCHARACTERRECOGNITION']._serialized_end=930
# @@protoc_insertion_point(module_scope)
