# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.proto import base_pb2 as base__pb2
from core.proto import upload_service_pb2 as upload__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in upload_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UploadStub(object):
    """Image and Video Upload Service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImage = channel.unary_unary(
                '/upload.Upload/UploadImage',
                request_serializer=upload__service__pb2.UploadImageRequest.SerializeToString,
                response_deserializer=upload__service__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.UploadVideo = channel.unary_unary(
                '/upload.Upload/UploadVideo',
                request_serializer=upload__service__pb2.UploadVideoRequest.SerializeToString,
                response_deserializer=upload__service__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/upload.Upload/HealthCheck',
                request_serializer=base__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=base__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class UploadServicer(object):
    """Image and Video Upload Service.
    """

    def UploadImage(self, request, context):
        """Upload one or more images for caching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadVideo(self, request, context):
        """Upload one or more videos for frame extraction and caching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=upload__service__pb2.UploadImageRequest.FromString,
                    response_serializer=upload__service__pb2.UploadResponse.SerializeToString,
            ),
            'UploadVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadVideo,
                    request_deserializer=upload__service__pb2.UploadVideoRequest.FromString,
                    response_serializer=upload__service__pb2.UploadResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=base__pb2.HealthCheckRequest.FromString,
                    response_serializer=base__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'upload.Upload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('upload.Upload', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Upload(object):
    """Image and Video Upload Service.
    """

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upload.Upload/UploadImage',
            upload__service__pb2.UploadImageRequest.SerializeToString,
            upload__service__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upload.Upload/UploadVideo',
            upload__service__pb2.UploadVideoRequest.SerializeToString,
            upload__service__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upload.Upload/HealthCheck',
            base__pb2.HealthCheckRequest.SerializeToString,
            base__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
